# the docker-compose file provides services that can be optionally used for e.g. storage

version: "3"
services:
  postgresql:
    image: "postgres:alpine"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
