// Code generated by go-mockgen-tool: https://github.com/jamesrr39/go-mockgen-tool. DO NOT EDIT.

package diskfilemap

import (
	"github.com/jamesrr39/goutil/errorsx"
)

type MockOnDiskCollection struct {
	GetFunc      func(key []byte) ([]byte, error) 
	SetFunc      func(key []byte, value []byte) errorsx.Error 
	IteratorFunc func() (Iterator, errorsx.Error) 
}

func (o *MockOnDiskCollection) Get(key []byte) ([]byte, error) {
	if o.GetFunc == nil {
		panic("GetFunc not defined")
	}
	return o.GetFunc(key)
}

func (o *MockOnDiskCollection) Set(key []byte, value []byte) errorsx.Error {
	if o.SetFunc == nil {
		panic("SetFunc not defined")
	}
	return o.SetFunc(key, value)
}

func (o *MockOnDiskCollection) Iterator() (Iterator, errorsx.Error) {
	if o.IteratorFunc == nil {
		panic("IteratorFunc not defined")
	}
	return o.IteratorFunc()
}
