// Code generated by "stringer -type=MatchLevel"; DO NOT EDIT.

package ownmapdal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MatchLevelNone-0]
	_ = x[MatchLevelPartial-1]
	_ = x[MatchLevelFull-2]
}

const _MatchLevel_name = "MatchLevelNoneMatchLevelPartialMatchLevelFull"

var _MatchLevel_index = [...]uint8{0, 14, 31, 45}

func (i MatchLevel) String() string {
	if i < 0 || i >= MatchLevel(len(_MatchLevel_index)-1) {
		return "MatchLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MatchLevel_name[_MatchLevel_index[i]:_MatchLevel_index[i+1]]
}
