#!/usr/bin/env python3

styles = ''

with open('mss_files.txt', 'r') as f:
    for line in f.readlines():
        line = line.rstrip('\n')
        if line == '':
            continue

        with open(line, 'r') as style_file:
            style_from_sheet = style_file.read()
            styles += style_from_sheet.replace("`", "'") # escape backtips



out = '''// Code generated by {script_name}. DO NOT EDIT.

package osmstyles

const OSMStylesheet = `{styles}`
'''.format(script_name=__file__, styles=styles)

with open('bundled_styles.go', 'w') as outfile:
    outfile.write(out)
